"use client";
import React,{useEffect,useState} from "react";
const INSTAGRAM_URL="https://www.instagram.com/ehrenpils";
const kiosks=[
{name:"The Korner Kiosk",address:"Venloer Straße 270, 50823 Köln",maps:"https://maps.app.goo.gl/tHGtCk64D96LviQp9"},
{name:"Jeff's Kiosk",address:"Helmholtzstraße 2, 50825 Ehrenfeld",maps:"https://maps.app.goo.gl/mjcanTChtKmZ9uxL8"},
{name:"Ehrenkiosk",address:"Vogelsanger Str. 191, 50825 Ehrenfeld",maps:"https://maps.app.goo.gl/qgSJSHgQRLGFCfHW8"},
{name:"Venlo Kiosk",address:"Venloer Str. 394, 50825 Ehrenfeld",maps:"https://maps.app.goo.gl/YcYqN48gtodUaAer9"},
{name:"Minis Kiosk",address:"Vogelsanger Str. 199, 50825 Ehrenfeld",maps:"https://maps.app.goo.gl/3DQwnCLtapz2aJNe8"}];
const copy={de:{beer:"Bier",buy:"Kaufen",age:"BIST DU 16 ODER ÄLTER?",no:"Nein",yes:"Ja",remember:"Auswahl auf diesem Gerät merken",top:"BIER. KEIN MANIFEST.",hero:"GEHT REIN.",meta:"0,33 L · X,X % VOL.",cold:"HIER STEHT'S KALT.",where:"WO GIBT'S DAS?",legal:"Impressum",privacy:"Datenschutz"},en:{beer:"Beer",buy:"Buy",age:"ARE YOU 16 OR OLDER?",no:"Not yet",yes:"Yes",remember:"Remember on this device",top:"BEER. NO MANIFESTO.",hero:"GOES DOWN WELL.",meta:"0.33 L · X.X% ABV",cold:"KEPT COLD HERE.",where:"WHERE TO GET IT?",legal:"Legal notice",privacy:"Privacy"}} as const;
type Lang=keyof typeof copy;
function Insta(){return <svg viewBox="0 0 24 24" className="instagram-icon"><rect x="3" y="3" width="18" height="18" rx="5" fill="none" stroke="currentColor" strokeWidth="2"/><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" strokeWidth="2"/><circle cx="17.4" cy="6.7" r="1.15" fill="currentColor"/></svg>}
function LS({lang,setLang}:{lang:Lang,setLang:(l:Lang)=>void}){return <div className="language-switch"><button className={lang==="de"?"active":""} onClick={()=>setLang("de")}>DE</button><span>/</span><button className={lang==="en"?"active":""} onClick={()=>setLang("en")}>EN</button></div>}
export default function EhrenPage(){
const[lang,setLangState]=useState<Lang>("de");const[age,setAge]=useState(false);const[remember,setRemember]=useState(true);
useEffect(()=>{const s=localStorage.getItem("ehren-lang");const l:Lang=s==="de"||s==="en"?s:(navigator.language.toLowerCase().startsWith("de")?"de":"en");setLangState(l);document.documentElement.lang=l;setAge(localStorage.getItem("ehren-age-ok")!=="1")},[]);
const setLang=(l:Lang)=>{setLangState(l);localStorage.setItem("ehren-lang",l);document.documentElement.lang=l};const go=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:"smooth"});const t=copy[lang];
return <main className="ehren-page">
{age&&<div className="age-gate"><div className="age-language"><LS lang={lang} setLang={setLang}/></div><div className="age-card"><img src="/EHRENFELD_Wordmark-Horizontal_Cream_RGB_4096px.png" className="age-logo" alt="Ehrenfeld"/><h1>{t.age}</h1><div className="age-actions"><button onClick={()=>location.href="https://www.google.com"}>{t.no}</button><button onClick={()=>{if(remember)localStorage.setItem("ehren-age-ok","1");setAge(false)}}>{t.yes}</button></div><label className="remember-age"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/><span>{t.remember}</span></label></div></div>}
<header className="ehren-header"><div className="header-inner"><button className="brand" onClick={()=>go("home")}><img src="/HEADER-LOGO3.png" className="brand-logo" alt="Ehrenfeld"/></button><nav className="main-nav"><button className="nav-art-button" onClick={()=>go("home")} aria-label={t.beer}><img src="/NAV-BIER-CREAM.png" alt="" className="nav-art nav-art-beer" /></button><button className="nav-art-button" onClick={()=>go("kaufen")} aria-label={t.buy}><img src="/NAV-KAUFEN-CREAM.png" alt="" className="nav-art nav-art-buy" /></button><a href={INSTAGRAM_URL} target="_blank" rel="noopener noreferrer"><Insta/></a><LS lang={lang} setLang={setLang}/></nav></div></header>
<section className="hero" id="home"><div className="hero-inner"><div className="hero-copy"><img src="/HERO-geht-rein.png" alt={`${t.top} ${t.hero} ${t.meta}`} className="hero-typo-art" /></div><div className="bottle-placeholder">FINAL BOTTLE<br/>VISUAL</div></div><button className="scroll-cue" onClick={()=>go("kaufen")}>↓</button></section>
<section className="buy" id="kaufen"><div className="buy-inner"><div className="kiosk-list">{kiosks.map(k=><a href={k.maps} target="_blank" rel="noopener noreferrer" key={k.name}><span className="pin">●</span><span><strong>{k.name}</strong><small>{k.address}</small></span></a>)}</div><div className="buy-heading"><img src="/HERO-wo-gibts.png" alt={`${t.cold} ${t.where}`} className="buy-typo-art" /></div></div></section>
<footer><div className="footer-inner"><div className="footer-brand"><img src="/EHRENFELD_Octagonal-Badge_Cream_RGB_4096px.png" className="footer-logo" alt="Ehrenfeld"/><div className="copyright">© 2026 Ehrendrinks UG</div></div><nav className="footer-col"><button onClick={()=>go("home")}>{t.beer.toUpperCase()}</button><button onClick={()=>go("kaufen")}>{t.buy.toUpperCase()}</button><a href={INSTAGRAM_URL} target="_blank" rel="noopener noreferrer">INSTAGRAM</a></nav><nav className="footer-col"><LS lang={lang} setLang={setLang}/><a href="/impressum">{t.legal.toUpperCase()}</a><a href="/datenschutz">{t.privacy.toUpperCase()}</a></nav></div></footer>
</main>}
