"use client";
import React,{useCallback,useEffect,useState}from"react";
const eur=(n:any)=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(Number(n||0));
async function js(r:Response){const t=await r.text();if(!t.trim())throw Error(`Leere Serverantwort (${r.status})`);return JSON.parse(t)}
export default function CostCentersSection(){
 const[d,setD]=useState<any>({costCenters:[]}),[err,setErr]=useState(""),[showArchive,setShowArchive]=useState(false),[modal,setModal]=useState(false),[f,setF]=useState<any>({id:null,code:"",name:"",description:""});
 const load=useCallback(async()=>{try{const r=await fetch(`/api/backend/cost-centers?archived=${showArchive?1:0}`,{cache:"no-store"}),x=await js(r);if(!r.ok)throw Error(x.error);setD(x);setErr("")}catch(e){setErr(e instanceof Error?e.message:"Fehler")}},[showArchive]);
 useEffect(()=>{void load()},[load]);
 const edit=(x?:any)=>{setF(x?{id:x.id,code:x.code,name:x.name||"",description:x.description||""}:{id:null,code:"",name:"",description:""});setModal(true)};
 const save=async()=>{try{const r=await fetch("/api/backend/cost-centers",{method:f.id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(f)}),x=await js(r);if(!r.ok)throw Error(x.error);setModal(false);await load()}catch(e){setErr(e instanceof Error?e.message:"Fehler")}};
 const archive=async(x:any)=>{if(!confirm(x.active?`Kostenstelle ${x.code} archivieren?`:`Kostenstelle ${x.code} reaktivieren?`))return;try{const r=await fetch("/api/backend/cost-centers",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:x.id,active:!x.active})}),z=await js(r);if(!r.ok)throw Error(z.error);await load()}catch(e){setErr(e instanceof Error?e.message:"Fehler")}};
 return <>{err&&<div className="backend-inline-alert">{err}</div>}
 <section className="backend-section cost-center-section"><div className="backend-section-head"><div><span className="backend-section-kicker">CONTROLLING</span><h2>Kostenstellen</h2></div><div className="cost-center-head-actions"><button className="backend-secondary-action" onClick={()=>setShowArchive(v=>!v)}>{showArchive?"Aktive anzeigen":"Archiv anzeigen"}</button><button className="backend-primary-action" onClick={()=>edit()}>+ Neue Kostenstelle</button></div></div>
 <div className="backend-table-wrap"><table className="backend-table"><thead><tr><th>Code</th><th>Name</th><th>Einnahmen</th><th>Ausgaben</th><th>Saldo</th><th>Status</th><th></th></tr></thead><tbody>{d.costCenters.length?d.costCenters.map((x:any)=><tr key={x.id}><td><strong>{x.code}</strong></td><td>{x.name||"–"}</td><td>{eur(x.income)}</td><td>{eur(x.expenses)}</td><td><strong>{eur(Number(x.income)-Number(x.expenses))}</strong></td><td>{x.active?"Aktiv":"Archiviert"}</td><td><button className="backend-text-button" onClick={()=>edit(x)}>Bearbeiten</button> <button className="backend-text-button" onClick={()=>void archive(x)}>{x.active?"Archivieren":"Reaktivieren"}</button></td></tr>):<tr><td colSpan={7}>Keine Kostenstellen vorhanden.</td></tr>}</tbody></table></div></section>
 {modal&&<div className="backend-modal-backdrop"><div className="backend-modal"><div className="backend-modal-head"><div><span className="backend-section-kicker">KOSTENSTELLE</span><h2>{f.id?"Kostenstelle bearbeiten":"Neue Kostenstelle"}</h2></div><button className="backend-modal-close" onClick={()=>setModal(false)}>×</button></div><div className="backend-form-grid"><label><span>Code</span><input value={f.code} onChange={e=>setF({...f,code:e.target.value})} placeholder="2026-011-..."/></label><label><span>Name</span><input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label className="backend-form-full"><span>Beschreibung</span><textarea value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label></div><div className="backend-modal-actions"><button className="backend-secondary-action" onClick={()=>setModal(false)}>Abbrechen</button><button className="backend-primary-action" onClick={()=>void save()}>Speichern</button></div></div></div>}</>;
}
