"use client";
import React,{useCallback,useState}from"react";
const eur=(n:any)=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(Number(n||0));
const dd=(v:any)=>{if(!v)return"–";const d=new Date(String(v).slice(0,10)+"T00:00:00");return Number.isNaN(d.getTime())?"–":d.toLocaleDateString("de-DE")};
const today=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
async function js(r:Response){const t=await r.text();if(!t.trim())throw Error(`Leere Serverantwort (${r.status})`);return JSON.parse(t)}
export default function FinanceSection(){
 const[d,setD]=useState<any>({transactions:[],reserves:[],documents:[],contacts:[],costCenters:[],totals:{}}),[modal,setModal]=useState(""),[err,setErr]=useState(""),[f,setF]=useState<any>({date:today(),service_date:today(),amount:"",net_amount:"",tax_rate:"19",description:"",payment_method:"Bankkonto"}),[settings,setSettings]=useState<any>({}),[warehouseMovements,setWarehouseMovements]=useState<any[]>([]);
 const load=useCallback(async()=>{try{const r=await fetch("/api/backend/finance",{cache:"no-store"}),x=await js(r);if(!r.ok)throw Error(x.error);setD(x);setErr("")}catch(e){setErr(e instanceof Error?e.message:"Fehler")}},[]);
 React.useEffect(()=>{void load()},[load]);
 const reset=async(m:string)=>{setErr("");setF({date:today(),service_date:today(),amount:"",net_amount:"",tax_rate:"19",description:"",payment_method:"Bankkonto"});setModal(m);if(m==="incoming"){try{const r=await fetch("/api/backend/finance/incoming-invoices/warehouse-movements",{cache:"no-store"}),x=await js(r);if(r.ok)setWarehouseMovements(x.movements||[])}catch{setWarehouseMovements([])}}};
 const openSettings=async()=>{try{const r=await fetch("/api/backend/finance/settings",{cache:"no-store"}),x=await js(r);if(!r.ok)throw Error(x.error);setSettings(x.settings||{});setModal("settings")}catch(e){setErr(e instanceof Error?e.message:"Fehler")}};
 const save=async()=>{try{
   if(modal==="settings"){const r=await fetch("/api/backend/finance/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(settings)}),x=await js(r);if(!r.ok)throw Error(x.error);setModal("");return}
   if(modal==="incoming"){
     const fd=new FormData();fd.set("supplier_id",String(f.supplier_id||""));fd.set("external_document_number",f.external_document_number||"");fd.set("document_date",f.date);fd.set("service_date",f.service_date||f.date);fd.set("cost_center_id",String(f.cost_center_id||""));fd.set("linked_warehouse_movement_id",String(f.linked_warehouse_movement_id||""));fd.set("net_amount",String(f.net_amount||""));fd.set("tax_rate",String(f.tax_rate||19));fd.set("note",f.note||"");if(f.file)fd.set("file",f.file);
     const r=await fetch("/api/backend/finance/incoming-invoices",{method:"POST",body:fd}),x=await js(r);if(!r.ok)throw Error(x.error);setModal("");await load();return;
   }
   const url=modal==="reserve"?"/api/backend/finance/reserves":modal==="cash"?"/api/backend/finance/cash":"/api/backend/finance";
   const description=String(f.description||"").trim()||((modal==="capitalin"?"Gründereinlage":modal==="capitalout"?"Gründerentnahme":"")+(f.capital_person_name?` · ${f.capital_person_name}`:""));
   const body=modal==="reserve"?{name:f.description,planned_amount:+f.amount,cost_center_id:f.cost_center_id||null,due_date:f.date,note:f.note}:modal==="cash"?{date:f.date,account_name:f.account_name||"Bankkonto",amount:+f.amount,note:f.note}:{transaction_type:modal==="expense"?"EXPENSE":modal==="income"?"INCOME":modal==="capitalin"?"CAPITAL_IN":"CAPITAL_OUT",date:f.date,amount:+f.amount,description,cost_center_id:f.cost_center_id||null,address_book_id:f.address_book_id||null,reserve_id:f.reserve_id||null,payment_method:f.payment_method,capital_person_name:f.capital_person_name||null,note:f.note};
   const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),x=await js(r);if(!r.ok)throw Error(x.error);setModal("");await load()
 }catch(e){setErr(e instanceof Error?e.message:"Fehler")}};
 const pay=async(id:number)=>{if(!confirm("Als bezahlt verbuchen?"))return;try{const r=await fetch(`/api/backend/finance/documents/${id}/pay`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({date:today(),payment_method:"Bankkonto"})}),x=await js(r);if(!r.ok)throw Error(x.error);await load()}catch(e){setErr(e instanceof Error?e.message:"Fehler")}};
 const t=d.totals||{},openOut=d.documents.filter((x:any)=>x.direction==="OUTGOING"&&x.status==="OPEN").reduce((s:number,x:any)=>s+Number(x.gross_amount||0),0),openIn=d.documents.filter((x:any)=>x.direction==="INCOMING"&&x.status==="OPEN").reduce((s:number,x:any)=>s+Number(x.gross_amount||0),0);
 const suppliers=d.contacts.filter((x:any)=>Array.isArray(x.types)&&x.types.includes("supplier")),tax=Number(f.net_amount||0)*Number(f.tax_rate||0)/100,gross=Number(f.net_amount||0)+tax;
 const title:any={expense:"Ausgabe außerhalb Lager",income:"Sonstige Einnahme",capitalin:"Gründereinlage",capitalout:"Gründerentnahme",reserve:"Rückstellung",cash:"Kontostand aktualisieren"};
 return <>{err&&<div className="backend-inline-alert">{err}</div>}
 <section className="finance-summary-grid">{[["Kontostand",t.cash==null?"–":eur(t.cash)],["Offene Forderungen",eur(openOut)],["Offene Verbindlichkeiten",eur(openIn)],["Gründereinlagen",eur(t.capital_in)],["Rückstellungen offen",eur(t.reserved)]].map(x=><article key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></article>)}</section>
 <div className="finance-actions"><button className="backend-primary-action" onClick={()=>void reset("expense")}>− Ausgabe außerhalb Lager</button><button className="backend-secondary-action" onClick={()=>void reset("income")}>+ Sonstige Einnahme</button><button className="backend-secondary-action" onClick={()=>void reset("capitalin")}>+ Gründereinlage</button><button className="backend-secondary-action" onClick={()=>void reset("capitalout")}>− Gründerentnahme</button><button className="backend-secondary-action" onClick={()=>void reset("reserve")}>+ Rückstellung</button><button className="backend-secondary-action" onClick={()=>void reset("cash")}>Kontostand aktualisieren</button><button className="backend-secondary-action" onClick={()=>void openSettings()}>Rechnungsdaten</button></div>
 <section className="backend-section"><div className="backend-section-head"><div><span className="backend-section-kicker">FINANZEN</span><h2>Rechnungen & Belege</h2></div><button className="backend-primary-action" onClick={()=>void reset("incoming")}>+ Eingangsrechnung</button></div>
 <div className="backend-table-wrap"><table className="backend-table"><thead><tr><th>Datum</th><th>Nr.</th><th>Art</th><th>Von / Zu</th><th>Kostenstelle</th><th>Netto</th><th>MwSt.</th><th>Brutto</th><th>Status</th><th>Dokument</th><th></th></tr></thead><tbody>{d.documents.length?d.documents.map((x:any)=><tr key={x.id}><td>{dd(x.document_date)}</td><td>{x.direction==="OUTGOING"?<a className="backend-table-link" href={`/backend/rechnung/${x.id}`} target="_blank">{x.document_number}</a>:<strong>{x.external_document_number||x.document_number}</strong>}</td><td>{x.direction==="INCOMING"?"Eingangsrechnung":x.document_type==="ZERO_RECEIPT"?"0-€-Beleg":x.document_type==="INTERNAL"?"Interner Beleg":"Ausgangsrechnung"}</td><td>{x.contact_name||"–"}</td><td>{x.cost_center_code||"–"}</td><td>{eur(x.net_amount)}</td><td>{eur(x.tax_amount)}</td><td><strong>{eur(x.gross_amount)}</strong></td><td>{x.status==="OPEN"?"Offen":x.status==="PAID"?"Bezahlt":"Erledigt"}</td><td>{x.direction==="INCOMING"&&x.attachment_name?<a className="backend-table-link" href={`/api/backend/finance/documents/${x.id}?download=1`} target="_blank">PDF</a>:"–"}</td><td>{x.status==="OPEN"&&<button className="backend-text-button" onClick={()=>void pay(x.id)}>Als bezahlt markieren</button>}</td></tr>):<tr><td colSpan={11}>Noch keine Belege.</td></tr>}</tbody></table></div></section>
 <section className="backend-section"><div className="backend-section-head"><div><span className="backend-section-kicker">PLANUNG</span><h2>Rückstellungen</h2></div></div><div className="backend-table-wrap"><table className="backend-table"><thead><tr><th>Rückstellung</th><th>Kostenstelle</th><th>Geplant</th><th>Verwendet</th><th>Rest</th><th>Fällig</th></tr></thead><tbody>{d.reserves.length?d.reserves.map((x:any)=><tr key={x.id}><td>{x.name}</td><td>{x.cost_center_code||"–"}</td><td>{eur(x.planned_amount)}</td><td>{eur(x.used_amount)}</td><td>{eur(Math.max(0,+x.planned_amount-+x.used_amount))}</td><td>{dd(x.due_date)}</td></tr>):<tr><td colSpan={6}>Keine Rückstellungen.</td></tr>}</tbody></table></div></section>
 <section className="backend-section"><div className="backend-section-head"><div><span className="backend-section-kicker">GELDFLUSS</span><h2>Finanzbewegungen</h2><p className="finance-section-note">Hier landen tatsächliche Geldbewegungen: manuelle Einnahmen/Ausgaben, Gründereinlagen und -entnahmen sowie Rechnungen in dem Moment, in dem sie als bezahlt markiert werden.</p></div></div><div className="backend-table-wrap"><table className="backend-table"><thead><tr><th>Datum</th><th>Art</th><th>Beschreibung</th><th>Von / Zu</th><th>Kostenstelle</th><th>Rückstellung</th><th>Betrag</th><th>User</th></tr></thead><tbody>{d.transactions.map((x:any)=><tr key={x.id}><td>{dd(x.transaction_date)}</td><td>{{INCOME:"Einnahme",EXPENSE:"Ausgabe",CAPITAL_IN:"Gründereinlage",CAPITAL_OUT:"Gründerentnahme"}[x.transaction_type]||x.transaction_type}</td><td>{x.description}</td><td>{x.capital_person_name||x.contact_name||"–"}</td><td>{x.cost_center_code||"–"}</td><td>{x.reserve_name||"–"}</td><td>{eur(x.amount)}</td><td>{x.user_name||"–"}</td></tr>)}</tbody></table></div></section>
 {modal&&<div className="backend-modal-backdrop"><div className="backend-modal"><div className="backend-modal-head"><div><span className="backend-section-kicker">FINANZEN</span><h2>{modal==="incoming"?"Eingangsrechnung erfassen":modal==="settings"?"Rechnungsdaten":title[modal]}</h2></div><button className="backend-modal-close" onClick={()=>setModal("")}>×</button></div>
 {modal==="incoming"?<div className="backend-form-grid">
  <label><span>Lieferant</span><select value={f.supplier_id||""} onChange={async e=>{const supplier_id=+e.target.value;setF({...f,supplier_id,linked_warehouse_movement_id:""});try{const r=await fetch(`/api/backend/finance/incoming-invoices/warehouse-movements?supplier_id=${supplier_id}`,{cache:"no-store"}),x=await js(r);if(r.ok)setWarehouseMovements(x.movements||[])}catch{}}}><option value="">Bitte wählen</option>{suppliers.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
  <label className="backend-form-full"><span>Zugehöriger Wareneingang (optional)</span><select value={f.linked_warehouse_movement_id||""} onChange={e=>{const id=+e.target.value,m=warehouseMovements.find((x:any)=>Number(x.id)===id);if(!m){setF({...f,linked_warehouse_movement_id:""});return}setF({...f,linked_warehouse_movement_id:id,supplier_id:Number(m.supplier_id)||f.supplier_id,cost_center_id:Number(m.cost_center_id)||"",service_date:String(m.movement_date).slice(0,10),net_amount:Number(m.net_total).toFixed(2)})}}><option value="">Keine Lagerbuchung verknüpfen</option>{warehouseMovements.map((m:any)=><option key={m.id} value={m.id} disabled={m.already_linked}>{dd(m.movement_date)} · {m.product_name} · {Number(m.quantity).toLocaleString("de-DE")} {m.unit} · {eur(m.unit_cost)}/Stk. · {eur(m.net_total)} netto{m.already_linked?" · bereits verknüpft":""}</option>)}</select><small className="product-field-help">Bei Auswahl werden Lieferant, Kostenstelle, Leistungsdatum und Netto automatisch aus dem Wareneingang übernommen. Alles bleibt editierbar.</small></label>
  <label><span>Rechnungsnummer Lieferant</span><input value={f.external_document_number||""} onChange={e=>setF({...f,external_document_number:e.target.value})}/></label>
  <label><span>Rechnungsdatum</span><input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></label><label><span>Leistungsdatum</span><input type="date" value={f.service_date} onChange={e=>setF({...f,service_date:e.target.value})}/></label>
  <label><span>Kostenstelle</span><select value={f.cost_center_id||""} onChange={e=>setF({...f,cost_center_id:+e.target.value})}><option value="">Keine</option>{d.costCenters.map((x:any)=><option key={x.id} value={x.id}>{x.code}</option>)}</select></label>
  {f.linked_warehouse_movement_id&&(()=>{const m=warehouseMovements.find((x:any)=>Number(x.id)===Number(f.linked_warehouse_movement_id));return m?<label><span>Übernommen</span><input disabled value={`${Number(m.quantity).toLocaleString("de-DE")} ${m.unit} × ${eur(m.unit_cost)} netto`}/></label>:null})()}<label><span>Netto</span><input type="number" min="0" step=".01" value={f.net_amount||""} onChange={e=>setF({...f,net_amount:e.target.value})}/></label>
  <label><span>MwSt.</span><select value={f.tax_rate} onChange={e=>setF({...f,tax_rate:e.target.value})}><option value="19">19 %</option><option value="7">7 %</option><option value="0">0 %</option></select></label>
  <label><span>Brutto</span><input disabled value={eur(gross)}/></label>
  <label className="backend-form-full"><span>PDF (optional, max. 10 MB)</span><input type="file" accept="application/pdf" onChange={e=>setF({...f,file:e.target.files?.[0]||null})}/></label>
  <label className="backend-form-full"><span>Notiz</span><textarea value={f.note||""} onChange={e=>setF({...f,note:e.target.value})}/></label>
 </div>:modal==="settings"?<div className="backend-form-grid">{[["issuer_name","Firma / Rechnungssteller"],["issuer_street","Straße"],["issuer_postal_code","PLZ"],["issuer_city","Ort"],["issuer_country","Land"],["tax_number","Steuernummer"],["vat_id","USt-IdNr."],["iban","IBAN"],["bic","BIC"],["bank_name","Bank"]].map(([k,l])=><label key={k}><span>{l}</span><input value={settings[k]||""} onChange={e=>setSettings({...settings,[k]:e.target.value})}/></label>)}</div>:<div className="backend-form-grid"><label><span>Beschreibung</span><input value={f.description||""} onChange={e=>setF({...f,description:e.target.value})}/></label><label><span>Betrag</span><input type="number" min="0" step=".01" value={f.amount||""} onChange={e=>setF({...f,amount:e.target.value})}/></label><label><span>Datum</span><input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></label>{(modal==="capitalin"||modal==="capitalout")&&<><label><span>Art</span><input disabled value={modal==="capitalin"?"Gründereinlage · Eigenkapital":"Gründerentnahme · Eigenkapital"}/></label><label><span>Von / Zu</span><input value={f.capital_person_name||""} onChange={e=>setF({...f,capital_person_name:e.target.value})} placeholder={modal==="capitalin"?"Von wem?":"An wen?"}/></label><label><span>Kostenstelle</span><select value={f.cost_center_id||""} onChange={e=>setF({...f,cost_center_id:e.target.value?+e.target.value:null})}><option value="">Keine</option>{d.costCenters.map((x:any)=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label></>}{(modal==="expense"||modal==="income")&&<label><span>Kostenstelle</span><select value={f.cost_center_id||""} onChange={e=>setF({...f,cost_center_id:e.target.value?+e.target.value:null})}><option value="">Keine</option>{d.costCenters.map((x:any)=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label>}{modal==="reserve"&&<label><span>Kostenstelle</span><select value={f.cost_center_id||""} onChange={e=>setF({...f,cost_center_id:e.target.value?+e.target.value:null})}><option value="">Keine</option>{d.costCenters.map((x:any)=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label>}{modal==="cash"&&<label><span>Konto</span><input value={f.account_name||"Bankkonto"} onChange={e=>setF({...f,account_name:e.target.value})}/></label>}<label className="backend-form-full"><span>Notiz</span><textarea value={f.note||""} onChange={e=>setF({...f,note:e.target.value})}/></label></div>}
 <div className="backend-modal-actions"><button className="backend-secondary-action" onClick={()=>setModal("")}>Abbrechen</button><button className="backend-primary-action" onClick={()=>void save()}>Speichern</button></div></div></div>}</>}
