"use client";
import React,{useCallback,useEffect,useState} from "react";
type P={id:number;name:string;category:string;unit:string;batch_tracking:boolean;selling_price:string|number|null;tax_rate:string|number|null;active:boolean};
type F={name:string;category:"Getränk"|"Marketing"|"Ausstattung";unit:string;batch_tracking:boolean;selling_price:string;tax_rate:string};
const blank:F={name:"",category:"Getränk",unit:"Stück",batch_tracking:false,selling_price:"0.00",tax_rate:"19"};
const categories:F["category"][]=["Getränk","Marketing","Ausstattung"];
async function json(r:Response){const t=await r.text();if(!t.trim())throw new Error(`Leere Serverantwort (HTTP ${r.status}).`);return JSON.parse(t)}
export default function ProductsSection(){const [rows,setRows]=useState<P[]>([]),[arch,setArch]=useState(false),[edit,setEdit]=useState<P|null>(null),[open,setOpen]=useState(false),[form,setForm]=useState<F>(blank),[err,setErr]=useState("");
const load=useCallback(async()=>{try{const r=await fetch(`/api/backend/products?archived=${arch?1:0}`,{cache:"no-store"}),d=await json(r);if(!r.ok)throw new Error(d.error||"Fehler");setRows(d.products||[]);setErr("")}catch(e){setErr(e instanceof Error?e.message:"Fehler")}},[arch]);useEffect(()=>{void load()},[load]);
const save=async()=>{try{const r=await fetch(edit?`/api/backend/products/${edit.id}`:"/api/backend/products",{method:edit?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,selling_price:Number(form.selling_price||0),tax_rate:Number(form.tax_rate||0)})}),d=await json(r);if(!r.ok)throw new Error(d.error||"Fehler");setOpen(false);setEdit(null);setForm(blank);await load()}catch(e){setErr(e instanceof Error?e.message:"Fehler")}};
const status=async(p:P)=>{if(!confirm(p.active?"Produkt archivieren? Bestand und Historie bleiben erhalten.":"Produkt reaktivieren?"))return;const r=await fetch(`/api/backend/products/${p.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({active:!p.active})}),d=await json(r);if(!r.ok)return setErr(d.error||"Fehler");await load()};
const del=async(p:P)=>{if(!confirm("Produkt endgültig löschen? Nur möglich, wenn es nie verwendet wurde."))return;const r=await fetch(`/api/backend/products/${p.id}`,{method:"DELETE"}),d=await json(r);if(!r.ok)return setErr(d.error||"Fehler");await load()};
return <><section className="backend-section backend-section-first"><div className="backend-section-head"><div><span className="backend-section-kicker">STAMMDATEN</span><h2>Produkte</h2></div><div className="warehouse-actions compact-actions"><button className="backend-secondary-action" onClick={()=>setArch(v=>!v)}>{arch?"Aktive anzeigen":"Archiv anzeigen"}</button><button className="backend-primary-action" onClick={()=>{setEdit(null);setForm(blank);setOpen(true)}}>+ Neues Produkt</button></div></div>{err&&<div className="backend-inline-alert">{err}</div>}<div className="backend-table-wrap"><table className="backend-table"><thead><tr><th>Produkt</th><th>Kategorie</th><th>Einheit</th><th>Standard-VK netto</th><th>MwSt.</th><th>Chargenführung</th><th>Status</th><th></th></tr></thead><tbody>{rows.length?rows.map(p=><tr key={p.id}><td><strong>{p.name}</strong></td><td>{p.category}</td><td>{p.unit}</td><td className="backend-number">{new Intl.NumberFormat("de-DE",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(p.selling_price||0))} €</td><td>{Number(p.tax_rate||0).toLocaleString("de-DE",{maximumFractionDigits:2})} %</td><td>{p.batch_tracking?"Ja":"Nein"}</td><td>{p.active?"Aktiv":"Archiviert"}</td><td><div className="addressbook-row-actions"><button onClick={()=>{setEdit(p);setForm({name:p.name,category:(categories.includes(p.category as F["category"])?p.category:"Ausstattung") as F["category"],unit:p.unit,batch_tracking:p.batch_tracking,selling_price:String(Number(p.selling_price||0).toFixed(2)),tax_rate:String(Number(p.tax_rate||19))});setOpen(true)}}>Bearbeiten</button><button onClick={()=>void status(p)}>{p.active?"Archivieren":"Reaktivieren"}</button><button className="danger" onClick={()=>void del(p)}>Löschen</button></div></td></tr>):<tr><td colSpan={8}>Keine Produkte vorhanden.</td></tr>}</tbody></table></div></section>
{open&&<div className="backend-modal-backdrop"><div className="backend-modal"><div className="backend-modal-head"><div><span className="backend-section-kicker">PRODUKTE</span><h2>{edit?"Produkt bearbeiten":"Neues Produkt"}</h2></div><button className="backend-modal-close" onClick={()=>setOpen(false)}>×</button></div><div className="backend-form-grid"><label className="backend-form-full"><span>Produkt</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label><span>Kategorie</span><select value={form.category} onChange={e=>setForm({...form,category:e.target.value as F["category"]})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Einheit</span><input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})} placeholder="z. B. Flaschen, Stück, Gläser"/></label><label className="backend-form-full"><span>Standard-Verkaufspreis netto / Einheit</span><input type="number" min="0" step="0.01" value={form.selling_price} onChange={e=>setForm({...form,selling_price:e.target.value})}/><small className="product-field-help">0,00 € ist erlaubt; Marge wird aus dem Ø Einstand berechnet.</small></label><label><span>MwSt.</span><select value={form.tax_rate} onChange={e=>setForm({...form,tax_rate:e.target.value})}><option value="19">19 %</option><option value="7">7 %</option><option value="0">0 %</option></select></label><label className="backend-form-full product-batch-checkbox"><input type="checkbox" checked={form.batch_tracking} onChange={e=>setForm({...form,batch_tracking:e.target.checked})}/><span>Chargenführung verwenden</span></label></div><div className="backend-modal-actions"><button className="backend-secondary-action" onClick={()=>setOpen(false)}>Abbrechen</button><button className="backend-primary-action" onClick={()=>void save()}>Speichern</button></div></div></div>}</>}
