import { NextResponse } from "next/server";
import { auth, clerkClient } from "@clerk/nextjs/server";
import { sql } from "../../../../lib/db";
async function allowed(){const{userId}=await auth();if(!userId)return false;const c=await clerkClient(),u=await c.users.getUser(userId);return u.publicMetadata?.ehrenmann===true}
type State={q:number;v:number};
export async function GET(r:Request){if(!await allowed())return NextResponse.json({error:"Nicht autorisiert"},{status:403});try{const url=new URL(r.url),requested=Number(url.searchParams.get("year")),current=new Date().getFullYear();const ys=await sql`SELECT DISTINCT y::int AS fiscal_year FROM (SELECT EXTRACT(YEAR FROM document_date) y FROM commercial_documents UNION SELECT substring(code from 1 for 4)::int y FROM cost_centers WHERE code ~ '^[0-9]{4}-') x WHERE y IS NOT NULL ORDER BY y DESC`;const years=(ys as any[]).map(x=>Number(x.fiscal_year)),year=Number.isInteger(requested)&&requested>2000?requested:(years[0]||current);
const docs=await sql`SELECT direction,status,COALESCE(net_amount,0)::float8 net,COALESCE(tax_amount,0)::float8 tax,cost_center_id,warehouse_movement_id FROM commercial_documents WHERE EXTRACT(YEAR FROM document_date)=${year} AND status<>'CANCELLED'`;let revenue=0,opex=0,outputVat=0,inputVat=0;const byCc=new Map<number,{revenue:number;expenses:number}>(),cc=(id:number)=>{if(!byCc.has(id))byCc.set(id,{revenue:0,expenses:0});return byCc.get(id)!};for(const d of docs as any[]){const net=Number(d.net||0),tax=Number(d.tax||0),id=Number(d.cost_center_id||0);if(d.direction==='OUTGOING'){revenue+=net;outputVat+=tax;if(id)cc(id).revenue+=net}else if(d.direction==='INCOMING'){inputVat+=tax;if(!d.warehouse_movement_id){opex+=net;if(id)cc(id).expenses+=net}}}
const moves=await sql`SELECT movement_date::text,movement_type,product_id,quantity::float8 quantity,COALESCE(unit_cost,0)::float8 unit_cost,source_location_id,destination_location_id FROM warehouse_movements ORDER BY movement_date,id`;const states=new Map<string,State>(),get=(p:number,l:number)=>{const k=`${p}:${l}`;if(!states.has(k))states.set(k,{q:0,v:0});return states.get(k)!};let cogs=0;for(const m of moves as any[]){const p=Number(m.product_id),q=Number(m.quantity||0),y=Number(String(m.movement_date).slice(0,4));if(!p||q<=0)continue;if(['IN','RETURN'].includes(String(m.movement_type))){const l=Number(m.destination_location_id);if(!l)continue;const st=get(p,l),uc=Number(m.unit_cost||0);st.q+=q;st.v+=q*uc;if(m.movement_type==='RETURN'&&y===year)cogs-=q*uc}else if(m.movement_type==='TRANSFER'){const a=Number(m.source_location_id),b=Number(m.destination_location_id);if(!a||!b)continue;const s=get(p,a),avg=s.q>0?s.v/s.q:0,mv=Math.min(q,Math.max(s.q,0)),val=mv*avg;s.q-=mv;s.v-=val;const d=get(p,b);d.q+=mv;d.v+=val}else if(['OUT','SALE','LOSS'].includes(String(m.movement_type))){const l=Number(m.source_location_id);if(!l)continue;const st=get(p,l),avg=st.q>0?st.v/st.q:0,mv=Math.min(q,Math.max(st.q,0));st.q-=mv;st.v-=mv*avg;if(m.movement_type==='SALE'&&y===year)cogs+=mv*avg}}
cogs=Math.max(0,cogs);const grossProfit=revenue-cogs,ebitda=grossProfit-opex,depreciation=0,ebit=ebitda;const centers=await sql`SELECT id,code,name FROM cost_centers WHERE code LIKE ${year+'-%'} ORDER BY code`;const costCenters=(centers as any[]).map(c=>{const x=byCc.get(Number(c.id))||{revenue:0,expenses:0};return{code:c.code,name:c.name,revenue:x.revenue,expenses:x.expenses,result:x.revenue-x.expenses}});return NextResponse.json({year,years:years.includes(year)?years:[year,...years],kpis:{revenue,cogs,grossProfit,operatingExpenses:opex,ebitda,depreciation,ebit,outputVat,inputVat,vatBalance:outputVat-inputVat},costCenters})}catch(e){console.error('EBITDA_ERROR',e);return NextResponse.json({error:e instanceof Error?e.message:'EBITDA konnte nicht geladen werden.'},{status:500})}}
